### ISSUE TITLE
Contents

### ISSUE THREAD

**Issue by kks32** [RSE-Cambridge/hpc-containers#1]
Trying to map out a list of contents, so each item could be an issue.
## TOC
- [ ] What are containers
- [ ] An introduction to Docker (do we need this?)
- [ ] An introduction to Singularity (http://singularity.lbl.gov/user-guide)
- [ ] Running Singularity containers in HPC
- [ ] Creating Singularity Images
  - [ ] Building a Singularity image from scratch
  - [ ] Converting a docker image to singularity image
  - [ ] Singularity example (non-mpi)
  - [ ] Singularity example (mpi)
  - [ ] Singularity example (gpu)

**Comment by fspiga** [comment]
I am going to build a generic presentation for the first slot about containers in HPC and also underline specific elements of Singularity and Shifter. CSCS folks will cover Shifter more in-depth and Gregory from Singularity will go in-depth in his keynote.
